### PR TITLE
Feature/spfx182upgrade

### PR DESCRIPTION
**Pull request by baywet**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample/tool?     | no                               |
| Related issues? |  |

## Original Authors
@estruyf 
## What's in this Pull Request?
- Upgraded to spfx 1.8.2
- Switched to node 10 for pipeline
- Other minor tweaks for pipeline

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @baywet, appreciated. I'll merge this right away to master... not really 100% sure on the value of using dev branch with these.

**Comment by baywet** [comment]
thanks! @estruyf do you think we should get rid of the dev branch?

**Comment by VesaJuvonen** [comment]
in this repo yes - I don't think it adds that much value in here. It makes sense on for example for PnP PowerShell which has monthly release cycle, but not sure on the value here.

**Comment by baywet** [comment]
this repo has a mix of samples and Azure DevOps tasks (so code to maintain and ship)
And this repo https://github.com/SharePoint/sp-dev-fx-webparts has a dev branch as well even though it only contains samples. So I guess the original idea was to align it. But agreed, at the current size we don't necessary need it

**Comment by baywet** [comment]
I wanted to get @estruyf 's opinion though before making any change

**Comment by VesaJuvonen** [comment]
Technically there's no value on the dev branch in the web parts and extensions repos and was planning to get rid of it there as well. Open for discussion absolutely.

**Comment by baywet** [comment]
I think we agree for the samples. For any "real code" I do like to follow gitflow, even on small projects.
But maybe the issue is that this repo is a mix of things which doesn't help making a clear decision?

**Pull request merged**
