### PR TITLE
Update gupfile-upload-to-sharepoint.js

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
Allow all assets to be uploaded, not only .js files

### CODE REVIEW

**Comment by estruyf** [comment]
Looks good, thanks.

**Comment by joelfmrodrigues** [comment]
You're welcome

**Comment by VesaJuvonen** [comment]
thx Joel, appreciated.

**Comment by joelfmrodrigues** [comment]
I'm sure it took a very long time to review all my changes :D

**Pull request merged**
